#edition = "2021"
max_width = 100
attr_fn_like_width = 100
binop_separator = "Front"
wrap_comments = true
error_on_line_overflow = true
error_on_unformatted = true
fn_params_layout = "Tall"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hard_tabs = true
skip_macro_invocations = ["*"]
