[package]
name = "terminity"
version = "0.1.0"
authors = ["Gwennan Eliezer <naeiogalaxy@gmail.com>"]
edition = "2021"
default-run = "game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminity_widgets = { version = "*", path = "../terminity_widgets" }
crossterm = { version = "0.26", features = ["event-stream"] }
rand = "*"
#console = "0.15"
structopt = "0.3"
lazy_static = "1.4"
