[package]
name = "terminity_widgets_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = { version = "1", default-features = false }
#proc_macro_error = "1.0"
