[package]
name = "terminity_widgets_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro-error = { version = "1" }
syn = {version = "1.0", features = ["derive"]}
quote = "1.0"
#proc_macro_error = "1.0"
